name: Python Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create test outputs
        run: |
          mkdir -p tests
          echo 'def test_true():
              assert True' > tests/test_basic.py

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          python -m pytest tests/ -v