name: Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Setup
        run: |
          mkdir -p tests junit
          echo 'def test_true():\n    assert True' > tests/test_basic.py
      
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      - name: Run tests
        run: python -m pytest tests/test_basic.py -v
