name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-cov numpy pandas scikit-learn
        pip install torch --index-url https://download.pytorch.org/whl/cpu

    
    - name: Set up environment
      run: |
        mkdir -p tests/coverage
        touch tests/__init__.py
        chmod -R 777 tests/coverage
    
    - name: Run tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |

      uses: actions/upload-artifact@v4
      if: always()
      with:
